# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Convert Eigen matrix to Arma matrix
#'
#' @param eigen_A A matrix.
#' @author
#' Andrew DiLernia
#' @export
eigen2arma <- function(eigen_A) {
    .Call(`_pcCov_eigen2arma`, eigen_A)
}

arma2eigen <- function(arma_A) {
    .Call(`_pcCov_arma2eigen`, arma_A)
}

#' @export
eigenMult2 <- function(A, B) {
    .Call(`_pcCov_eigenMult2`, A, B)
}

#' @export
eigenMult3 <- function(A, B, C) {
    .Call(`_pcCov_eigenMult3`, A, B, C)
}

#' @export
eigenMult4 <- function(A, B, C, D) {
    .Call(`_pcCov_eigenMult4`, A, B, C, D)
}

#' @export
invCov2part_cpp <- function(icmat) {
    .Call(`_pcCov_invCov2part_cpp`, icmat)
}

#' @export
cov2corr_cpp <- function(cmat) {
    .Call(`_pcCov_cov2corr_cpp`, cmat)
}

#' @export
corrMat_cpp <- function(tsData, partial = TRUE) {
    .Call(`_pcCov_corrMat_cpp`, tsData, partial)
}

#' @export
cosTaper_cpp <- function(u) {
    .Call(`_pcCov_cosTaper_cpp`, u)
}

#' @export
expTaper_cpp <- function(u) {
    .Call(`_pcCov_expTaper_cpp`, u)
}

#' @export
crossCov_cpp <- function(u, ts1, ts2) {
    .Call(`_pcCov_crossCov_cpp`, u, ts1, ts2)
}

#' @export
crossCov2_cpp <- function(u, ts1, ts2) {
    .Call(`_pcCov_crossCov2_cpp`, u, ts1, ts2)
}

#' @export
taperCov_cpp <- function(ts1, ts2, banw) {
    .Call(`_pcCov_taperCov_cpp`, ts1, ts2, banw)
}

#' @export
taperCovSub_cpp <- function(ts1, ts2, banw, hu2s) {
    .Call(`_pcCov_taperCovSub_cpp`, ts1, ts2, banw, hu2s)
}

#' @export
upperTriFill_cpp <- function(n, x) {
    .Call(`_pcCov_upperTriFill_cpp`, n, x)
}

#' Taylor Series Estimate of Covariance Matrix for Partial Correlations
#'
#' This function calculates a second-order Taylor Series estimate of the covariance matrix for partial correlations of a weakly stationary multivariate time series.
#'
#' @param ts \eqn{nt} x \eqn{p} matrix of observed p-variate time series.
#' @param bw nonnegative bandwidth parameter.
#' @param iMatq matrix of indices for partial correlations equal to unique(royVarhelper(p)[, 1:2]).
#' @param iMate matrix of indices for partial correlations equal to royVarhelper(p, errors = T).
#' @param q number of unique partial correlations equal to choose(\eqn{p}, 2).
#'
#' @author
#' Andrew DiLernia
#'
#' @export
partialCov_cpp <- function(ts, bw, iMatq, iMate, q) {
    .Call(`_pcCov_partialCov_cpp`, ts, bw, iMatq, iMate, q)
}

thetaHat_cpp <- function(i, j, l, m, ts, n, hu2s, ccMat) {
    .Call(`_pcCov_thetaHat_cpp`, i, j, l, m, ts, n, hu2s, ccMat)
}

deltaHat_cpp <- function(i, j, l, m, mvts, n, hu2s, ccs, ccMat) {
    .Call(`_pcCov_deltaHat_cpp`, i, j, l, m, mvts, n, hu2s, ccs, ccMat)
}

#' @export
royVar_cpp <- function(iMat, tsData, q, bw = 10L) {
    .Call(`_pcCov_royVar_cpp`, iMat, tsData, q, bw)
}

#' @export
royVar2_cpp <- function(iMat, tsData, q) {
    .Call(`_pcCov_royVar2_cpp`, iMat, tsData, q)
}

#' @export
bdiagArray_cpp <- function(array3d) {
    .Call(`_pcCov_bdiagArray_cpp`, array3d)
}

xMaker_cpp <- function(K, q) {
    .Call(`_pcCov_xMaker_cpp`, K, q)
}

#' @export
arrayMean_cpp <- function(array3d) {
    .Call(`_pcCov_arrayMean_cpp`, array3d)
}

#' @export
upperTri_cpp <- function(m, incDiag = FALSE) {
    .Call(`_pcCov_upperTri_cpp`, m, incDiag)
}

thetaUpdate_cpp <- function(eVec, K, q) {
    .Call(`_pcCov_thetaUpdate_cpp`, eVec, K, q)
}

sigPsiInv_cpp <- function(sigmas, sigVal, qK, q, K) {
    .Call(`_pcCov_sigPsiInv_cpp`, sigmas, sigVal, qK, q, K)
}

arrayEigen_cpp <- function(array3d) {
    .Call(`_pcCov_arrayEigen_cpp`, array3d)
}

#' @export
eigen_cpp <- function(myMat) {
    .Call(`_pcCov_eigen_cpp`, myMat)
}

sigPsiInvBlks_cpp <- function(eigs, sigVal, q, K) {
    .Call(`_pcCov_sigPsiInvBlks_cpp`, eigs, sigVal, q, K)
}

XtSX_cpp <- function(blocks, q, K) {
    .Call(`_pcCov_XtSX_cpp`, blocks, q, K)
}

#' @export
royVcm_cpp <- function(ys, sigmas, sigEigs, delta = 0.001, maxIters = 100L, sig0 = 0.10) {
    .Call(`_pcCov_royVcm_cpp`, ys, sigmas, sigEigs, delta, maxIters, sig0)
}

listRoyVar_cpp <- function(ys, q, iMat) {
    .Call(`_pcCov_listRoyVar_cpp`, ys, q, iMat)
}

arrayRoyVar_cpp <- function(ys, q, iMat) {
    .Call(`_pcCov_arrayRoyVar_cpp`, ys, q, iMat)
}

royTest_cpp2 <- function(y1, y2, iMat, alpha = 0.05, multAdj = "holm-bonferroni", nperm = 100L) {
    .Call(`_pcCov_royTest_cpp2`, y1, y2, iMat, alpha, multAdj, nperm)
}

